import { createFileRoute } from "@tanstack/react-router";
import { PublicLayout, PageHeader } from "@/components/PublicLayout";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Use — OpportunityX" },
      { name: "description", content: "Terms covering accounts, demo opportunity data, premium billing and acceptable use of OpportunityX." },
      { property: "og:title", content: "Terms of Use — OpportunityX" },
      { property: "og:description", content: "Accounts, demo data, billing and acceptable use." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: TermsPage,
});

const SECTIONS = [
  { h: "Your account", p: "You are responsible for keeping your login credentials safe and for the accuracy of the profile details you enter." },
  { h: "Opportunity information", p: "Listings are realistic demonstration records. Always verify eligibility, deadlines and application steps on the official organiser website before applying." },
  { h: "Matching results", p: "Match scores are guidance generated by a rule-based engine. They are not a guarantee of eligibility, selection or any outcome." },
  { h: "Premium plan", p: "Premium is shown at ₹199 per month. In this demonstration build checkout is simulated and no payment is taken." },
  { h: "Acceptable use", p: "Do not scrape the catalogue, attempt to access other students' data, or upload content you do not own." },
  { h: "Changes", p: "These terms may be updated as the product evolves; continued use means you accept the current version." },
];

function TermsPage() {
  return (
    <PublicLayout>
      <PageHeader title="Terms of Use" subtitle="The ground rules for using OpportunityX." />
      <section className="mx-auto max-w-3xl space-y-8 px-4 py-14 sm:px-6">
        {SECTIONS.map((s) => (
          <div key={s.h} className="space-y-2">
            <h2 className="font-display text-lg font-semibold">{s.h}</h2>
            <p className="text-sm text-muted-foreground">{s.p}</p>
          </div>
        ))}
      </section>
    </PublicLayout>
  );
}
